CREATE DATABASE url_shortener;
USE url_shortener;

CREATE TABLE users(
 id INT AUTO_INCREMENT PRIMARY KEY,
 email VARCHAR(120) UNIQUE,
 password VARCHAR(255),
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE urls(
 id INT AUTO_INCREMENT PRIMARY KEY,
 user_id INT,
 long_url TEXT NOT NULL,
 short_code VARCHAR(10) UNIQUE,
 clicks INT DEFAULT 0,
 expiry DATETIME NULL,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(user_id) REFERENCES users(id)
);